project:
  type: website
  output-dir: docs

website:
  title: "PM566 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - source.qmd
      - appendix.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

